project_id = "sftnncffdhpfntocbfes"

[functions.hotmart-webhook]
verify_jwt = false

[functions.auto-login]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.auto-notifications]
verify_jwt = false
